### ISSUE TITLE
Fix Netlify functions

### ISSUE THREAD

**Issue by SiamKreative** [SiamKreative/website#24]
```
10:23:30 PM: 2020-09-15T15:23:30.813Z	3aff8175-9649-4a7b-a0e3-bef2a673972b	INFO	Sending the email
10:23:31 PM: 2020-09-15T15:23:31.459Z	3aff8175-9649-4a7b-a0e3-bef2a673972b	INFO	TypeError: Expected signal to be an instanceof AbortSignal    at new $ (/var/task/src/.functions/contact.js:1:127681)    at /var/task/src/.functions/contact.js:1:129004    at new Promise (<anonymous>)    at Object.W [as default] (/var/task/src/.functions/contact.js:1:128967)    at Object.e [as default] (/var/task/src/.functions/contact.js:1:154662)    at e.runAction (/var/task/src/.functions/contact.js:1:105915)    at e._createRecords (/var/task/src/.functions/contact.js:1:44290)    at e.create (/var/task/src/.functions/contact.js:1:13684)    at statusCode (/var/task/src/.functions/contact.js:1:48684)    at new Promise (<anonymous>)
10:23:31 PM: Duration: 650.01 ms	Memory Usage: 73 MB	Init Duration: 192.38 ms	
```

What the hell does this mean? It's working fine locally when running `netlify dev --functions=functions`

**Comment by SiamKreative** [comment]
https://github.com/Azure/ms-rest-nodeauth/issues/83#issuecomment-606522618

**Comment by SiamKreative** [comment]
```
6:58:43 PM: 2020-09-16T11:58:43.058Z	2784a8b9-5644-49af-bb72-cba54822d3d2	INFO	TypeError: Expected signal to be an instanceof AbortSignal    at new Request (/var/task/src/.functions/contact.js:13910:10)    at /var/task/src/.functions/contact.js:14097:19    at new Promise (<anonymous>)    at Object.fetch [as default] (/var/task/src/.functions/contact.js:14095:9)    at Object.runAction [as default] (/var/task/src/.functions/contact.js:17527:20)    at Base.runAction (/var/task/src/.functions/contact.js:11099:29)    at Table._createRecords (/var/task/src/.functions/contact.js:5529:20)    at Table.create (/var/task/src/.functions/contact.js:2254:16)    at /var/task/src/.functions/contact.js:6234:20    at new Promise (<anonymous>)
6:58:43 PM: Duration: 9.67 ms	Memory Usage: 70 MB	Init Duration: 173.21 ms	
```
